// ACTION TYPE

// PROFILE
export const NEW_POST_TEXT = 'NEW_POST_TEXT'
export const ADD_POST = 'ADD_POST'
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO'
export const SET_PROFILE_STATUS = 'SET_PROFILE_STATUS'


// MESSAGES
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const NEW_MESSAGE_TEXT = 'NEW_MESSAGE_TEXT'

// USERS
export const FOLLOW_TOGGLE = 'FOLLOW_TOGGLE'
export const SET_USERS = 'SET_USERS'
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE'
export const SET_USERS_TOTAL_COUNT = 'SET_USERS_TOTAL_COUNT'
export const IS_FETCH_TOGGLE = 'IS_FETCH_TOGGLE'
export const FOLLOW_FETCHING_TOGGLE = 'FOLLOW_FETCHING_TOGGLE'

//Auth
export const SET_USER_DATA = 'SET_USER_DATA'
export const IS_AUTH_TOGGLE = 'IS_AUTH_TOGGLE'